name = "poe-chat"
main = "src/index.ts"
compatibility_date = "2024-04-05"

[assets]
binding = "ASSETS"
directory = "./public"
# ls
[[d1_databases]]
binding = "DB"
database_name = "poe-db"
database_id = "4589c425-40e3-4d8b-80fd-4b34e19eb529"
