name = "poe-chat"
main = "src/index.ts"
compatibility_date = "2024-04-05"

[assets]
binding = "ASSETS"
directory = "./public"
# ls
[[d1_databases]]
binding = "DB"
database_name = "poe-db"
database_id = "4589c425-40e3-4d8b-80fd-4b34e19eb529"


# R2 存储桶绑定 (聊天媒体和图表共用)
[[r2_buckets]]
binding     = "R2_BUCKET"
bucket_name = "yuangs" # ✨ 请确保这是您正确的R2桶名称