name = "shici-app"
compatibility_date = "2025-12-22"

# 部署静态资产到 Cloudflare Workers KV
assets = { directory = "./", binding = "ASSETS" }

# 或者，如果你要部署一个 Worker 脚本
# main = "src/index.js"  # 取消注释并指定你的 Worker 入口文件